services:
  # auth-api:
  #   build: .
  #   command: ["/commands/run_local.sh"]
  #   container_name: auth-api
  #   image: fury_shipping-travel-settings-api
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   env_file: .env
  #   ports:
  #     - 8080:8080
  #   networks:
  #     - app-network
  #   restart: always

  postgres:
    image: postgres:17
    container_name: postgres
    ports:
      - "5432:5432"
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
